// CyberSkill Status Hub — sample data (fictional, on-brand). window.SH_DATA
window.SH_DATA = {
  updated: "18 Jul 2026, 13:20 ICT",
  velocity: [
    { wk: "W23", n: 4 }, { wk: "W24", n: 7 }, { wk: "W25", n: 5 },
    { wk: "W26", n: 9 }, { wk: "W27", n: 6 }, { wk: "W28", n: 11 }, { wk: "W29", n: 8 },
  ],
  projects: [
    { key: "CDS", name: "Design System v1.6", status: "active", pct: 72, blurb: "Liquid Glass component bindings + 15 element packs.",
      seg: { done: 62, active: 20, hold: 4, todo: 14 }, owner: "Design Lead", updated: "2h ago", squad: "Platform",
      tasks: [["TASK-DS-041","Glass surface bindings","done"],["TASK-DS-047","Element-pack verifier v2","active"],["TASK-DS-052","Dark-mode APCA re-check","active"],["TASK-DS-055","Figma variable sync","todo"]],
      risk: "" },
    { key: "GENIE", name: "Lumi Genie Chat", status: "active", pct: 58, blurb: "Keyless Claude proxy; scripted wish-capture flow.",
      seg: { done: 48, active: 24, hold: 8, todo: 20 }, owner: "AI Lead", updated: "5h ago", squad: "AI",
      tasks: [["TASK-CHAR-026","In-chat wish flow","done"],["TASK-CHAR-030","One-time mascot hint","active"],["TASK-CHAR-021","Golden-genie GLB","hold"]],
      risk: "GLB art asset is a hard external dependency — commission not yet confirmed (TASK-CHAR-021)." },
    { key: "SITE", name: "cyberskill.world", status: "active", pct: 84, blurb: "Bilingual storytelling landing; lead capture live.",
      seg: { done: 78, active: 12, hold: 0, todo: 10 }, owner: "Web Lead", updated: "1h ago", squad: "Growth",
      tasks: [["TASK-BIZ-003","Lead pipeline e2e","done"],["TASK-SEO-012","llms.txt route","done"],["TASK-CTA-020","Teardown funnel polish","active"]],
      risk: "" },
    { key: "OS", name: "CyberOS Agent Spine", status: "hold", pct: 41, blurb: "BRAIN memory store + HITL acceptance gates.",
      seg: { done: 36, active: 8, hold: 30, todo: 26 }, owner: "Eng Lead", updated: "1d ago", squad: "Platform",
      tasks: [["TASK-OS-018","Gate runner","done"],["TASK-OS-022","Memory compaction","hold"],["TASK-OS-025","Provenance ledger","hold"]],
      risk: "Blocked on infra: provenance ledger needs the signing service (target Q1 2027)." },
    { key: "AUDIT", name: "DS Audit Framework", status: "done", pct: 100, blurb: "125-criteria vendor-neutral audit; L3 tier held.",
      seg: { done: 100, active: 0, hold: 0, todo: 0 }, owner: "DesignOps", updated: "3d ago", squad: "Platform",
      tasks: [["TASK-AUD-009","Deterministic engine","done"],["TASK-AUD-011","No-regression CI gate","done"]],
      risk: "" },
    { key: "TOKENS", name: "Token Pipeline", status: "active", pct: 66, blurb: "DTCG → CSS/TS/Swift/Kotlin/Flutter/Figma.",
      seg: { done: 58, active: 22, hold: 0, todo: 20 }, owner: "Eng Lead", updated: "6h ago", squad: "Platform",
      tasks: [["TASK-TOK-014","Contrast grid export","done"],["TASK-TOK-019","Flutter target","active"],["TASK-TOK-021","Provenance JSON","todo"]],
      risk: "" },
  ],
  releases: [
    { ver: "v1.6.0", when: "This week", now: true, done: false, title: "Glass bindings + element-pack v2",
      items: ["Opt-in .cs-surface-* component bindings", "Element-pack verifier v2 (0 warnings across 15)", "Dark-mode APCA re-check"] },
    { ver: "v1.5.1", when: "04 Jul 2026", now: false, done: true, title: "15 element packs ship",
      items: ["All 15 packs promoted to shipped", "Per-pack screenshot regression", "Gallery build script"] },
    { ver: "v1.4.0", when: "13 Jun 2026", now: false, done: true, title: "Liquid Glass in code",
      items: ["--cs-glass-* + --cs-depth-* scalars", "glass.css material layer", "Reduced-transparency fallbacks"] },
    { ver: "v1.3.0", when: "14 May 2026", now: false, done: true, title: "Brand assets + Logo",
      items: ["Official master mark ships", "React <Logo> from master artwork", "Light becomes default theme"] },
  ],
};

// Vietnamese variants (kit fully EN⇄VN per owner decision, Jul 2026). window.SH_VI
window.SH_VI = {
  updated: "18/07/2026, 13:20 ICT",
  blurbs: { CDS: "Liên kết component Liquid Glass + 15 gói Ngũ Hành.", GENIE: "Proxy Claude không cần khóa; luồng tiếp nhận điều ước theo kịch bản.", SITE: "Trang giới thiệu song ngữ kể chuyện; thu lead đang chạy.", OS: "Kho nhớ BRAIN + cổng nghiệm thu có con người.", AUDIT: "Bộ kiểm định trung lập 125 tiêu chí; giữ hạng L3.", TOKENS: "DTCG → CSS/TS/Swift/Kotlin/Flutter/Figma." },
  risks: { GENIE: "Tài sản GLB là phụ thuộc ngoài khó — chưa chốt đặt hàng (TASK-CHAR-021).", OS: "Bị chặn bởi hạ tầng: sổ cái nguồn gốc cần dịch vụ ký số (mục tiêu Q1 2027)." },
  owners: { "Design Lead": "Trưởng thiết kế", "AI Lead": "Trưởng AI", "Web Lead": "Trưởng web", "Eng Lead": "Trưởng kỹ thuật", "DesignOps": "DesignOps" },
  squads: { Platform: "Nền tảng", AI: "AI", Growth: "Tăng trưởng" },
  updatedRel: { "2h ago": "2 giờ trước", "5h ago": "5 giờ trước", "1h ago": "1 giờ trước", "1d ago": "1 ngày trước", "3d ago": "3 ngày trước", "6h ago": "6 giờ trước" },
  relWhen: { "v1.6.0": "Tuần này", "v1.5.1": "04/07/2026", "v1.4.0": "13/06/2026", "v1.3.0": "14/05/2026" },
  relTitles: { "v1.6.0": "Liên kết Glass + gói Ngũ Hành v2", "v1.5.1": "15 gói Ngũ Hành ra mắt", "v1.4.0": "Liquid Glass vào mã", "v1.3.0": "Tài sản thương hiệu + Logo" },
  relItems: { "v1.6.0": ["Liên kết component .cs-surface-* (tùy chọn)", "Trình kiểm gói Ngũ Hành v2 (0 cảnh báo trên 15 gói)", "Kiểm tra lại APCA cho chế độ tối"], "v1.5.1": ["Cả 15 gói lên trạng thái đã ra mắt", "Regression ảnh chụp từng gói", "Script dựng gallery"], "v1.4.0": ["Scalar --cs-glass-* + --cs-depth-*", "Lớp chất liệu glass.css", "Fallback khi giảm độ trong suốt"], "v1.3.0": ["Master mark chính thức ra mắt", "<Logo> React từ artwork gốc", "Light thành theme mặc định"] },
};
