#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { createHash } from "node:crypto";

const ROOT = resolve(import.meta.dirname, "..");
const SRC = resolve(ROOT, "src/tokens.tokens.json");
const DIST = resolve(ROOT, "dist");
const source = readFileSync(SRC, "utf8");
const data = JSON.parse(source);

function walkTokens(node, path = [], out = []) {
  if (!node || typeof node !== "object") return out;
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    if (value && typeof value === "object" && "$value" in value) {
      out.push({ path: [...path, key], token: value });
    } else {
      walkTokens(value, [...path, key], out);
    }
  }
  return out;
}

function tokenName(path) {
  return path.join(".");
}

const tokens = walkTokens(data);
const byName = new Map(tokens.map((entry) => [tokenName(entry.path), entry.token]));

function resolveValue(value, stack = []) {
  if (typeof value !== "string") return value;
  const match = value.match(/^\{(.+)\}$/);
  if (!match) return value;
  const ref = match[1];
  if (stack.includes(ref)) throw new Error(`Circular token alias: ${[...stack, ref].join(" -> ")}`);
  const next = byName.get(ref);
  if (!next) throw new Error(`Unresolved token alias: ${ref}`);
  return resolveValue(next.$value, [...stack, ref]);
}

function validate() {
  const errors = [];
  for (const { path, token } of tokens) {
    const name = tokenName(path);
    if (!token.$type) errors.push(`${name}: missing $type`);
    if (!("$value" in token)) errors.push(`${name}: missing $value`);
    if (!token.$description) errors.push(`${name}: missing $description`);
    try {
      resolveValue(token.$value);
    } catch (error) {
      errors.push(`${name}: ${error.message}`);
    }
  }
  if (errors.length) throw new Error(errors.join("\n"));
}

function ensure(path) {
  mkdirSync(path, { recursive: true });
}

function cssVarName(path) {
  return `--${path.join("-")}`;
}

function hexToRgb(hex) {
  const clean = hex.replace("#", "");
  const n = parseInt(clean, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function srgb(channel) {
  const c = channel / 255;
  return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

function luminance(hex) {
  const [r, g, b] = hexToRgb(hex).map(srgb);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(a, b) {
  const l1 = luminance(a);
  const l2 = luminance(b);
  const high = Math.max(l1, l2);
  const low = Math.min(l1, l2);
  return (high + 0.05) / (low + 0.05);
}

function write(path, body) {
  ensure(dirname(path));
  writeFileSync(path, body);
}

validate();

const resolved = tokens.map(({ path, token }) => ({
  name: tokenName(path),
  css: cssVarName(path),
  type: token.$type,
  value: resolveValue(token.$value),
  raw: token.$value,
  description: token.$description
}));

const css = [
  "/* Generated by @cyberskill/tokens. Do not edit directly. */",
  ":root {",
  "  /* Light is the default theme. Dark/system are opt-in via [data-theme] (see @cyberskill/react theme layer). */",
  "  color-scheme: light;",
  ...resolved.map((token) => `  ${token.css}: ${token.value};`),
  "}",
  ""
].join("\n");

const js = [
  "/* Generated by @cyberskill/tokens. Do not edit directly. */",
  "export const tokens = " + JSON.stringify(resolved, null, 2) + ";",
  "export default tokens;",
  ""
].join("\n");

const dts = [
  "export interface CsToken { name: string; css: string; type: string; value: string | number; raw: string | number; description: string; }",
  "export declare const tokens: CsToken[];",
  "export default tokens;",
  ""
].join("\n");

const swift = [
  "// Generated by @cyberskill/tokens. Do not edit directly.",
  "public enum CSTokens {",
  ...resolved.map((token) => `  public static let ${token.name.replace(/[^a-zA-Z0-9]/g, "_")} = "${token.value}"`),
  "}",
  ""
].join("\n");

const kt = [
  "// Generated by @cyberskill/tokens. Do not edit directly.",
  "object CSTokens {",
  ...resolved.map((token) => `  const val ${token.name.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase()} = "${token.value}"`),
  "}",
  ""
].join("\n");

const dart = [
  "// Generated by @cyberskill/tokens. Do not edit directly.",
  "class CSTokens {",
  ...resolved.map((token) => `  static const String ${token.name.replace(/[^a-zA-Z0-9]/g, "_")} = "${token.value}";`),
  "}",
  ""
].join("\n");

const figma = JSON.stringify({
  generatedAt: new Date().toISOString(),
  sourceHash: createHash("sha256").update(source).digest("hex"),
  collections: [
    {
      name: "CyberSkill Prototype",
      modes: ["light"],
      variables: resolved
    }
  ]
}, null, 2) + "\n";

const contrastPairs = [
  ["cs.color.text.primary", "cs.color.surface.page"],
  ["cs.color.text.inverse", "cs.color.brand.umber"],
  ["cs.color.text.accent", "cs.color.surface.page"],
  ["cs.component.button.primary.fg", "cs.component.button.primary.bg"]
];

const contrastCsv = [
  "foreground,background,foreground_value,background_value,wcag_ratio,wcag_aa_body",
  ...contrastPairs.map(([fg, bg]) => {
    const fgValue = resolveValue(byName.get(fg).$value);
    const bgValue = resolveValue(byName.get(bg).$value);
    const ratio = contrast(fgValue, bgValue);
    return `${fg},${bg},${fgValue},${bgValue},${ratio.toFixed(2)},${ratio >= 4.5}`;
  })
].join("\n") + "\n";

const provenance = JSON.stringify({
  package: "@cyberskill/tokens",
  maturity: "Prototype",
  generatedAt: new Date().toISOString(),
  source: "src/tokens.tokens.json",
  sourceHash: createHash("sha256").update(source).digest("hex"),
  outputs: [
    "dist/css/tokens.css",
    "dist/ts/tokens.js",
    "dist/ts/tokens.d.ts",
    "dist/swift/Tokens.swift",
    "dist/kt/CSTokens.kt",
    "dist/flutter/cs_tokens.dart",
    "dist/rn/tokens.js",
    "dist/figma/variables.json",
    "dist/contrast-grid.csv"
  ]
}, null, 2) + "\n";

write(resolve(DIST, "css/tokens.css"), css);
write(resolve(DIST, "ts/tokens.js"), js);
write(resolve(DIST, "ts/tokens.d.ts"), dts);
write(resolve(DIST, "swift/Tokens.swift"), swift);
write(resolve(DIST, "kt/CSTokens.kt"), kt);
write(resolve(DIST, "flutter/cs_tokens.dart"), dart);
write(resolve(DIST, "rn/tokens.js"), js);
write(resolve(DIST, "figma/variables.json"), figma);
write(resolve(DIST, "contrast-grid.csv"), contrastCsv);
write(resolve(DIST, "build-provenance.json"), provenance);

console.log(`[tokens] built ${resolved.length} tokens`);
