#!/usr/bin/env node
/**
 * build-tokens.mjs — multi-platform token build
 * ─────────────────────────────────────────────
 *
 * Reads DTCG 2025.10 token files from `tokens/`, emits:
 *   - packages/tokens/dist/tokens.css   (CSS custom properties, all 4 modes)
 *   - packages/tokens/dist/tokens.mjs   (ESM constants)
 *   - packages/tokens/dist/tokens.d.ts  (TypeScript types)
 *   - packages/tokens/dist/Tokens.swift (Swift enum stub for iOS consumers)
 *   - packages/tokens/dist/tokens.xml   (Android resource stub)
 *
 * Closes audit criterion A5.3 (Token pipeline) → 5 and A6.3 (cross-platform
 * parity) → 4 path.
 *
 * Zero-dependency Node ESM. Uses only Node 20+ built-ins.
 * Per RFC 2026-003 § Phase 2 Wave 1 + roadmap-to-l5.md §4.2.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SRC = resolve(ROOT, 'tokens');
const OUT = resolve(ROOT, 'packages/tokens/dist');

if (!existsSync(OUT)) mkdirSync(OUT, { recursive: true });

// ─── Load all token files ──────────────────────────────────────────────

const files = readdirSync(SRC).filter((f) => f.endsWith('.tokens.json')).sort();
const sources = {};
for (const f of files) {
  const name = basename(f, '.tokens.json');
  sources[name] = JSON.parse(readFileSync(resolve(SRC, f), 'utf8'));
}

// ─── Helpers ───────────────────────────────────────────────────────────

const isToken = (v) => v && typeof v === 'object' && '$value' in v;

/** Walk a DTCG tree; yield {path, value, type, ext} for each leaf token. */
function* walk(node, prefix = []) {
  if (!node || typeof node !== 'object') return;
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    if (isToken(v)) {
      yield {
        path: [...prefix, k],
        value: v.$value,
        type: v.$type ?? null,
        ext: v.$extensions ?? null,
        description: v.$description ?? null,
      };
    } else if (v && typeof v === 'object') {
      yield* walk(v, [...prefix, k]);
    }
  }
}

const cssVarName = (segments) => '--cs-' + segments.map((s) => s.toLowerCase().replace(/[^a-z0-9-]/g, '-')).join('-');
const jsConstName = (segments) => 'CS_' + segments.map((s) => s.toUpperCase().replace(/[^A-Z0-9]/g, '_')).join('_');
const swiftCaseName = (segments) => segments.map((s, i) => i === 0 ? s.replace(/[^a-zA-Z0-9]/g, '') : s.charAt(0).toUpperCase() + s.slice(1).replace(/[^a-zA-Z0-9]/g, '')).join('');
const xmlResName = (segments) => 'cs_' + segments.map((s) => s.toLowerCase().replace(/[^a-z0-9]/g, '_')).join('_');

const resolveAlias = (v, sources) => {
  if (typeof v !== 'string') return v;
  if (!v.startsWith('{') || !v.endsWith('}')) return v;
  const ref = v.slice(1, -1);
  // ref is like "color.warm-white"; navigate sources
  const parts = ref.split('.');
  const head = parts[0] === 'color' ? 'colour' : parts[0];
  let cursor = sources[head];
  if (!cursor) return v;
  // first nav into top-level domain matching the file
  cursor = cursor[parts[0]] ?? cursor[head];
  for (let i = 1; i < parts.length; i++) {
    if (cursor == null) return v;
    cursor = cursor[parts[i]];
  }
  if (isToken(cursor)) return resolveAlias(cursor.$value, sources);
  return v;
};

const flatTokens = [];
for (const [_, json] of Object.entries(sources)) {
  for (const t of walk(json)) flatTokens.push(t);
}

// ─── 1) Emit CSS — with 4 modes via [data-theme] attribute ─────────────

const themeModes = ['light', 'dark', 'high-contrast', 'sepia'];

function buildCss() {
  const lines = ['/* Generated by scripts/build-tokens.mjs — do not edit by hand. */'];
  lines.push(':root {');
  for (const t of flatTokens) {
    const v = resolveAlias(t.value, sources);
    if (typeof v !== 'string' && typeof v !== 'number') continue;
    lines.push(`  ${cssVarName(t.path)}: ${v};`);
  }
  lines.push('}');

  // Per-mode overrides driven by $extensions.com.cyberskill.theme
  for (const mode of themeModes) {
    if (mode === 'light') continue; // base is light
    const overrides = [];
    for (const t of flatTokens) {
      const themeExt = t.ext?.['com.cyberskill.theme'];
      if (themeExt && themeExt[mode] !== undefined) {
        overrides.push(`  ${cssVarName(t.path)}: ${themeExt[mode]};`);
      }
    }
    if (overrides.length) {
      lines.push('');
      lines.push(`[data-theme="${mode}"] {`);
      lines.push(...overrides);
      lines.push('}');
    }
  }
  return lines.join('\n') + '\n';
}

writeFileSync(resolve(OUT, 'tokens.css'), buildCss());

// ─── 2) Emit JS / TS / D.TS ────────────────────────────────────────────

function buildMjs() {
  const lines = ['// Generated by scripts/build-tokens.mjs — do not edit by hand.'];
  for (const t of flatTokens) {
    const v = resolveAlias(t.value, sources);
    const literal = typeof v === 'number' ? v : JSON.stringify(v);
    lines.push(`export const ${jsConstName(t.path)} = ${literal};`);
  }
  return lines.join('\n') + '\n';
}

function buildDts() {
  const lines = ['// Generated by scripts/build-tokens.mjs — do not edit by hand.'];
  for (const t of flatTokens) {
    const tsType = (t.type === 'number' || t.type === 'fontWeight') ? 'number' : 'string';
    lines.push(`export const ${jsConstName(t.path)}: ${tsType};`);
  }
  return lines.join('\n') + '\n';
}

writeFileSync(resolve(OUT, 'tokens.mjs'), buildMjs());
writeFileSync(resolve(OUT, 'tokens.d.ts'), buildDts());

// ─── 3) Emit Swift enum stub ───────────────────────────────────────────

function buildSwift() {
  const lines = [
    '// Generated by scripts/build-tokens.mjs — do not edit by hand.',
    '// CyberSkill design tokens for iOS / macOS consumers.',
    '// Phase 2 Wave 2 will expand this into typed UIKit / SwiftUI primitives.',
    '',
    'import Foundation',
    '#if canImport(UIKit)',
    'import UIKit',
    '#elseif canImport(AppKit)',
    'import AppKit',
    '#endif',
    '',
    'public enum CSTokens {',
  ];
  for (const t of flatTokens) {
    const v = resolveAlias(t.value, sources);
    if (typeof v !== 'string' && typeof v !== 'number') continue;
    const name = swiftCaseName(t.path);
    if (typeof v === 'number') {
      lines.push(`  public static let ${name}: Double = ${v}`);
    } else {
      lines.push(`  public static let ${name}: String = ${JSON.stringify(v)}`);
    }
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

writeFileSync(resolve(OUT, 'Tokens.swift'), buildSwift());

// ─── 4) Emit Android XML resource stub ─────────────────────────────────

function buildXml() {
  const lines = [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by scripts/build-tokens.mjs — do not edit by hand. -->',
    '<!-- CyberSkill design tokens for Android consumers. -->',
    '<resources>',
  ];
  for (const t of flatTokens) {
    const v = resolveAlias(t.value, sources);
    if (typeof v !== 'string' && typeof v !== 'number') continue;
    const name = xmlResName(t.path);
    let kind = 'string';
    if (t.type === 'color' && typeof v === 'string' && v.startsWith('#')) kind = 'color';
    else if (t.type === 'dimension') kind = 'dimen';
    else if (t.type === 'number' || t.type === 'fontWeight') kind = 'integer';
    lines.push(`  <${kind} name="${name}">${v}</${kind}>`);
  }
  lines.push('</resources>');
  return lines.join('\n') + '\n';
}

writeFileSync(resolve(OUT, 'tokens.xml'), buildXml());

// ─── Done ──────────────────────────────────────────────────────────────

const sizes = {
  css: buildCss().length,
  mjs: buildMjs().length,
  dts: buildDts().length,
  swift: buildSwift().length,
  xml: buildXml().length,
};

console.log(`[build-tokens] Emitted ${flatTokens.length} tokens to packages/tokens/dist/:`);
for (const [k, v] of Object.entries(sizes)) {
  console.log(`  - tokens.${k.padEnd(5)} ${v.toLocaleString()} chars`);
}
