// CyberSkill Design System — native design tokens.
// GENERATED from tokens/tokens.dtcg.json — do not hand-edit; regenerate on token change.
// release v1.0.0 · generated 2026-07-22T05:41:35.508Z · source sha256 4995d751afc8e47a…
// conversions: rem→px at 16 · em→…Em relative doubles · rgba alpha→ARGB byte (round(a*255)) · durations in ms
// dark element packs: see $extensions.overrides.elementsDark
// provenance: tokens/provenance.json · parity gate: _audit/token-pipeline-test.html

import SwiftUI

public enum CSTokens {
  /// 0xRRGGBB (+ alpha param) → SwiftUI Color
  public static func color(_ hex: UInt32, alpha: Double = 1) -> Color {
    Color(red: Double((hex >> 16) & 0xFF)/255, green: Double((hex >> 8) & 0xFF)/255, blue: Double(hex & 0xFF)/255, opacity: alpha)
  }

  public static let colorBrandUmber = color(0x45210E)
  public static let colorBrandOchre = color(0xF4BA17)
  public static let colorSurfacePage = color(0xFFFDF8)
  public static let colorSurfacePanel = color(0xFFFFFF)
  public static let colorSurfaceRaised = color(0xFBF4E9)
  public static let colorTextPrimary = color(0x45210E)
  public static let colorTextInverse = color(0xFFFFFF)
  public static let colorTextAccent = color(0x6E3B0E)
  public static let colorTextMuted = color(0x6E5A4C)
  public static let colorSemanticSuccess = color(0x166534)
  public static let colorSemanticDanger = color(0xB42318)
  public static let colorSemanticWarning = color(0x92400E)
  public static let colorSemanticInfo = color(0x1D4ED8)
  public static let colorAccentOchre = color(0xF4BA17)
  public static let colorBorderDefault = color(0xE7D9C6)
  public static let colorLink = color(0x6E3B0E)
  public static let colorLinkHover = color(0x45210E)
  public static let componentButtonPrimaryBg = color(0x45210E)
  public static let componentButtonPrimaryFg = color(0xFFFFFF)
  public static let componentButtonGap: CGFloat = 8
  public static let componentButtonRadius: CGFloat = 8
  public static let componentButtonSmPaddingY: CGFloat = 8
  public static let componentButtonSmPaddingX: CGFloat = 14
  public static let componentButtonSmMinHeight: CGFloat = 36
  public static let componentButtonMdPaddingY: CGFloat = 12
  public static let componentButtonMdPaddingX: CGFloat = 20
  public static let componentButtonMdMinHeight: CGFloat = 44
  public static let componentButtonLgPaddingY: CGFloat = 16
  public static let componentButtonLgPaddingX: CGFloat = 28
  public static let componentButtonLgMinHeight: CGFloat = 52
  public static let componentTextfieldBorderDefault = color(0xBFA58F)
  public static let componentTextfieldPaddingY: CGFloat = 10
  public static let componentTextfieldPaddingX: CGFloat = 12
  public static let componentTextfieldMinHeight: CGFloat = 44
  public static let accent = color(0xF4BA17)
  public static let accentStrong = color(0xB98200)
  public static let accentBright = color(0xF4BA17)
  public static let accentOn = color(0x45210E)
  public static let accentTint = color(0xFBF4E9)
  public static let accentInk = color(0x45210E)
  public static let accentGlow = color(0xF4BA17, alpha: 0.5)
  public static let accentGradA = color(0xF4BA17)
  public static let accentGradB = color(0xC77B4A)
  public static let depthBg: Double = 0
  public static let depthSection: Double = 5
  public static let depthCard: Double = 10
  public static let depthNav: Double = 50
  public static let depthModal: Double = 100
  public static let depthToast: Double = 200
  public static let glassWhisperBlur: CGFloat = 8
  public static let glassWhisperSaturate: String = "110%"
  public static let glassWhisperOpacity: String = "60%"
  public static let glassLightBlur: CGFloat = 12
  public static let glassLightSaturate: String = "130%"
  public static let glassLightOpacity: String = "70%"
  public static let glassStandardBlur: CGFloat = 16
  public static let glassStandardSaturate: String = "150%"
  public static let glassStandardOpacity: String = "80%"
  public static let glassHeavyBlur: CGFloat = 24
  public static let glassHeavySaturate: String = "180%"
  public static let glassHeavyOpacity: String = "90%"
  public static let shadowXs: String = "0 1px 2px rgba(69, 33, 14, 0.06)"
  public static let shadowSm: String = "0 1px 3px rgba(69, 33, 14, 0.04), 0 8px 24px rgba(69, 33, 14, 0.06)"
  public static let shadowMd: String = "0 12px 30px rgba(31, 19, 11, 0.18)"
  public static let shadowLg: String = "0 20px 60px rgba(69, 33, 14, 0.18)"
  public static let shadowXl: String = "0 24px 80px rgba(31, 19, 11, 0.26)"
  public static let durationInstantMs: Double = 0
  public static let durationFastMs: Double = 0
  public static let durationBaseMs: Double = 0
  public static let durationSlowMs: Double = 0
  public static let easeStandard: [Double] = [0.2, 0, 0, 1]
  public static let easeEntrance: [Double] = [0, 0, 0, 1]
  public static let easeExit: [Double] = [0.4, 0, 1, 1]
  public static let easeEmphasized: [Double] = [0.2, 0, 0, 1]
  public static let space0: CGFloat = 0
  public static let space1: CGFloat = 4
  public static let space2: CGFloat = 8
  public static let space3: CGFloat = 12
  public static let space4: CGFloat = 16
  public static let space5: CGFloat = 20
  public static let space6: CGFloat = 24
  public static let space8: CGFloat = 32
  public static let space10: CGFloat = 40
  public static let space12: CGFloat = 48
  public static let space16: CGFloat = 64
  public static let space20: CGFloat = 80
  public static let space24: CGFloat = 96
  public static let radiusSm: CGFloat = 4
  public static let radiusMd: CGFloat = 8
  public static let radiusLg: CGFloat = 14
  public static let radiusFull: CGFloat = 999
  public static let breakpointXs: CGFloat = 0
  public static let breakpointSm: CGFloat = 640
  public static let breakpointMd: CGFloat = 768
  public static let breakpointLg: CGFloat = 1024
  public static let breakpointXl: CGFloat = 1280
  public static let breakpoint2xl: CGFloat = 1536
  public static let containerMax: CGFloat = 1320
  public static let fontFamilyUi: String = "Be Vietnam Pro, ui-sans-serif, system-ui, sans-serif"
  public static let fontFamilyMono: String = "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
  public static let fontWeightRegular: Double = 400
  public static let fontWeightMedium: Double = 500
  public static let fontWeightSemibold: Double = 600
  public static let fontWeightBold: Double = 700
  public static let fontWeightExtrabold: Double = 800
  public static let fontLineHeightBody: Double = 1.5
  public static let fontLineHeightHeading: Double = 1.35
  public static let fontLineHeightTight: Double = 1.15
  public static let fontSizeXs: CGFloat = 12
  public static let fontSizeSm: CGFloat = 14
  public static let fontSizeBase: CGFloat = 16
  public static let fontSizeMd: CGFloat = 18
  public static let fontSizeLg: CGFloat = 20
  public static let fontSizeXl: CGFloat = 24
  public static let fontSize2xl: CGFloat = 30
  public static let fontSize3xl: CGFloat = 36
  public static let fontSize4xl: CGFloat = 48
  public static let fontSize5xl: CGFloat = 60
  public static let textDisplay: String = "var(--cs-font-size-5xl)"
  public static let textH1: String = "var(--cs-font-size-3xl)"
  public static let textH2: String = "var(--cs-font-size-2xl)"
  public static let textH3: String = "var(--cs-font-size-xl)"
  public static let textH4: String = "var(--cs-font-size-lg)"
  public static let textBodyLg: String = "var(--cs-font-size-md)"
  public static let textBody: String = "var(--cs-font-size-base)"
  public static let textSecondary: String = "var(--cs-font-size-sm)"
  public static let textCaption: String = "var(--cs-font-size-xs)"
  public static let textEyebrow: String = "var(--cs-font-size-xs)"
  public static let letterSpacingTightEm: Double = -0.01
  public static let letterSpacingNormal: Double = 0
  public static let letterSpacingCapsEm: Double = 0.08
  public static let iconSm: CGFloat = 16
  public static let iconMd: CGFloat = 20
  public static let iconLg: CGFloat = 24

  // MARK: dark-theme color overrides
  public static let colorSurfacePageDark = color(0x1A1108)
  public static let colorSurfacePanelDark = color(0x221710)
  public static let colorSurfaceRaisedDark = color(0x2B1E14)
  public static let colorTextPrimaryDark = color(0xF5EAD9)
  public static let colorTextInverseDark = color(0x1A1108)
  public static let colorTextAccentDark = color(0xF4BA17)
  public static let colorTextMutedDark = color(0xC9B7A3)
  public static let colorSemanticSuccessDark = color(0x4ADE80)
  public static let colorSemanticDangerDark = color(0xF87171)
  public static let colorSemanticWarningDark = color(0xFBBF24)
  public static let colorSemanticInfoDark = color(0x7CB2FB)
  public static let colorBorderDefaultDark = color(0x4A3A2C)
  public static let colorLinkDark = color(0xF4BA17)
  public static let colorLinkHoverDark = color(0xF5EAD9)
  public static let componentButtonPrimaryBgDark = color(0xF4BA17)
  public static let componentButtonPrimaryFgDark = color(0x1A1108)
  public static let componentTextfieldBorderDefaultDark = color(0x5A4636)

  // MARK: dark elemental accent packs (APCA-derived, v4.0.0)
  public static let accentBrightThoDark = color(0xFEC42C)
  public static let accentStrongThoDark = color(0x795507)
  public static let accentOnThoDark = color(0xF5EAD9)
  public static let accentTintThoDark = color(0x2F2203)
  public static let accentInkThoDark = color(0xFEC849)
  public static let accentThoClayDark = color(0xF3A372)
  public static let accentBrightThoClayDark = color(0xF4C5A3)
  public static let accentStrongThoClayDark = color(0x864927)
  public static let accentOnThoClayDark = color(0xF5EAD9)
  public static let accentTintThoClayDark = color(0x371C0B)
  public static let accentInkThoClayDark = color(0xF7C8A6)
  public static let accentStrongThoSandDark = color(0x725615)
  public static let accentOnThoSandDark = color(0xF5EAD9)
  public static let accentTintThoSandDark = color(0x2F2203)
  public static let accentInkThoSandDark = color(0xEFDCB2)
  public static let accentHoaDark = color(0xFB9E7A)
  public static let accentBrightHoaDark = color(0xFEC099)
  public static let accentStrongHoaDark = color(0x9F3405)
  public static let accentOnHoaDark = color(0xF5EAD9)
  public static let accentTintHoaDark = color(0x381B10)
  public static let accentInkHoaDark = color(0xFEC5A1)
  public static let accentHoaLavaDark = color(0xFE9982)
  public static let accentBrightHoaLavaDark = color(0xFFBF9E)
  public static let accentOnHoaLavaDark = color(0xF5EAD9)
  public static let accentTintHoaLavaDark = color(0x391A13)
  public static let accentInkHoaLavaDark = color(0xFFC4A5)
  public static let accentHoaPlasmaDark = color(0xFD97A3)
  public static let accentBrightHoaPlasmaDark = color(0xFDBECA)
  public static let accentStrongHoaPlasmaDark = color(0xA91A43)
  public static let accentOnHoaPlasmaDark = color(0xF5EAD9)
  public static let accentTintHoaPlasmaDark = color(0x38191D)
  public static let accentInkHoaPlasmaDark = color(0xFDC3CE)
  public static let accentThuyDark = color(0x7FC0CE)
  public static let accentBrightThuyDark = color(0xACD7E1)
  public static let accentOnThuyDark = color(0xF5EAD9)
  public static let accentTintThuyDark = color(0x042930)
  public static let accentInkThuyDark = color(0xAFDAE4)
  public static let accentThuyOceanDark = color(0x87B9DD)
  public static let accentBrightThuyOceanDark = color(0xB2D6EA)
  public static let accentOnThuyOceanDark = color(0xF5EAD9)
  public static let accentTintThuyOceanDark = color(0x08273A)
  public static let accentInkThuyOceanDark = color(0xB2D6EA)
  public static let accentStrongThuyMistDark = color(0x3F5F65)
  public static let accentOnThuyMistDark = color(0xF5EAD9)
  public static let accentTintThuyMistDark = color(0x0F282C)
  public static let accentInkThuyMistDark = color(0xC4DADD)
  public static let accentMocDark = color(0x9BBE78)
  public static let accentBrightMocDark = color(0xBFD88D)
  public static let accentStrongMocDark = color(0x44622D)
  public static let accentOnMocDark = color(0xF5EAD9)
  public static let accentTintMocDark = color(0x1C290D)
  public static let accentInkMocDark = color(0xC2DB90)
  public static let accentStrongMocBambooDark = color(0x4C6421)
  public static let accentOnMocBambooDark = color(0xF5EAD9)
  public static let accentTintMocBambooDark = color(0x1F280A)
  public static let accentInkMocBambooDark = color(0xC7D99E)
  public static let accentMocForestDark = color(0x9EBE8D)
  public static let accentBrightMocForestDark = color(0xBDD8A4)
  public static let accentOnMocForestDark = color(0xF5EAD9)
  public static let accentTintMocForestDark = color(0x19290F)
  public static let accentInkMocForestDark = color(0xC0DBA7)
  public static let accentStrongKimDark = color(0x675A4A)
  public static let accentOnKimDark = color(0xF5EAD9)
  public static let accentTintKimDark = color(0x2D220F)
  public static let accentInkKimDark = color(0xDBCFB9)
  public static let accentKimSteelDark = color(0xB2B6B6)
  public static let accentBrightKimSteelDark = color(0xCCD0D0)
  public static let accentStrongKimSteelDark = color(0x555B5D)
  public static let accentOnKimSteelDark = color(0xF5EAD9)
  public static let accentTintKimSteelDark = color(0x222525)
  public static let accentInkKimSteelDark = color(0xCFD3D3)
  public static let accentKimTitaniumDark = color(0xBFB3A5)
  public static let accentOnKimTitaniumDark = color(0xF5EAD9)
  public static let accentTintKimTitaniumDark = color(0x2B2217)
  public static let accentInkKimTitaniumDark = color(0xD9CFC0)
}
