// CyberSkill Design System — native design tokens.
// GENERATED from tokens/tokens.dtcg.json — do not hand-edit; regenerate on token change.
// release v1.0.0 · source sha256 4995d751afc8e47a…
// conversions: rem→px at 16 · em→…Em relative doubles · rgba alpha→ARGB byte (round(a*255)) · durations in ms
// dark element packs: see $extensions.overrides.elementsDark
// provenance: tokens/provenance.json · parity gate: _audit/token-pipeline-test.html

package world.cyberskill.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object CSTokens {
  val colorBrandUmber = Color(0xFF45210E)
  val colorBrandOchre = Color(0xFFF4BA17)
  val colorSurfacePage = Color(0xFFFFFDF8)
  val colorSurfacePanel = Color(0xFFFFFFFF)
  val colorSurfaceRaised = Color(0xFFFBF4E9)
  val colorTextPrimary = Color(0xFF45210E)
  val colorTextInverse = Color(0xFFFFFFFF)
  val colorTextAccent = Color(0xFF6E3B0E)
  val colorTextMuted = Color(0xFF6E5A4C)
  val colorSemanticSuccess = Color(0xFF166534)
  val colorSemanticDanger = Color(0xFFB42318)
  val colorSemanticWarning = Color(0xFF92400E)
  val colorSemanticInfo = Color(0xFF1D4ED8)
  val colorAccentOchre = Color(0xFFF4BA17)
  val colorBorderDefault = Color(0xFFE7D9C6)
  val colorLink = Color(0xFF6E3B0E)
  val colorLinkHover = Color(0xFF45210E)
  val componentButtonPrimaryBg = Color(0xFF45210E)
  val componentButtonPrimaryFg = Color(0xFFFFFFFF)
  val componentButtonGap = 8.dp
  val componentButtonRadius = 8.dp
  val componentButtonSmPaddingY = 8.dp
  val componentButtonSmPaddingX = 14.dp
  val componentButtonSmMinHeight = 36.dp
  val componentButtonMdPaddingY = 12.dp
  val componentButtonMdPaddingX = 20.dp
  val componentButtonMdMinHeight = 44.dp
  val componentButtonLgPaddingY = 16.dp
  val componentButtonLgPaddingX = 28.dp
  val componentButtonLgMinHeight = 52.dp
  val componentTextfieldBorderDefault = Color(0xFFBFA58F)
  val componentTextfieldPaddingY = 10.dp
  val componentTextfieldPaddingX = 12.dp
  val componentTextfieldMinHeight = 44.dp
  val accent = Color(0xFFF4BA17)
  val accentStrong = Color(0xFFB98200)
  val accentBright = Color(0xFFF4BA17)
  val accentOn = Color(0xFF45210E)
  val accentTint = Color(0xFFFBF4E9)
  val accentInk = Color(0xFF45210E)
  val accentGlow = Color(0x80F4BA17)
  val accentGradA = Color(0xFFF4BA17)
  val accentGradB = Color(0xFFC77B4A)
  val depthBg = 0
  val depthSection = 5
  val depthCard = 10
  val depthNav = 50
  val depthModal = 100
  val depthToast = 200
  val glassWhisperBlur = 8.dp
  val glassWhisperSaturate = "110%"
  val glassWhisperOpacity = "60%"
  val glassLightBlur = 12.dp
  val glassLightSaturate = "130%"
  val glassLightOpacity = "70%"
  val glassStandardBlur = 16.dp
  val glassStandardSaturate = "150%"
  val glassStandardOpacity = "80%"
  val glassHeavyBlur = 24.dp
  val glassHeavySaturate = "180%"
  val glassHeavyOpacity = "90%"
  val shadowXs = "0 1px 2px rgba(69, 33, 14, 0.06)"
  val shadowSm = "0 1px 3px rgba(69, 33, 14, 0.04), 0 8px 24px rgba(69, 33, 14, 0.06)"
  val shadowMd = "0 12px 30px rgba(31, 19, 11, 0.18)"
  val shadowLg = "0 20px 60px rgba(69, 33, 14, 0.18)"
  val shadowXl = "0 24px 80px rgba(31, 19, 11, 0.26)"
  val durationInstantMs = 0
  val durationFastMs = 0
  val durationBaseMs = 0
  val durationSlowMs = 0
  val easeStandard = doubleArrayOf(0.2, 0, 0, 1)
  val easeEntrance = doubleArrayOf(0, 0, 0, 1)
  val easeExit = doubleArrayOf(0.4, 0, 1, 1)
  val easeEmphasized = doubleArrayOf(0.2, 0, 0, 1)
  val space0 = 0.dp
  val space1 = 4.dp
  val space2 = 8.dp
  val space3 = 12.dp
  val space4 = 16.dp
  val space5 = 20.dp
  val space6 = 24.dp
  val space8 = 32.dp
  val space10 = 40.dp
  val space12 = 48.dp
  val space16 = 64.dp
  val space20 = 80.dp
  val space24 = 96.dp
  val radiusSm = 4.dp
  val radiusMd = 8.dp
  val radiusLg = 14.dp
  val radiusFull = 999.dp
  val breakpointXs = 0.dp
  val breakpointSm = 640.dp
  val breakpointMd = 768.dp
  val breakpointLg = 1024.dp
  val breakpointXl = 1280.dp
  val breakpoint2xl = 1536.dp
  val containerMax = 1320.dp
  val fontFamilyUi = "Be Vietnam Pro, ui-sans-serif, system-ui, sans-serif"
  val fontFamilyMono = "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
  val fontWeightRegular = 400
  val fontWeightMedium = 500
  val fontWeightSemibold = 600
  val fontWeightBold = 700
  val fontWeightExtrabold = 800
  val fontLineHeightBody = 1.5f
  val fontLineHeightHeading = 1.35f
  val fontLineHeightTight = 1.15f
  val fontSizeXs = 12.dp
  val fontSizeSm = 14.dp
  val fontSizeBase = 16.dp
  val fontSizeMd = 18.dp
  val fontSizeLg = 20.dp
  val fontSizeXl = 24.dp
  val fontSize2xl = 30.dp
  val fontSize3xl = 36.dp
  val fontSize4xl = 48.dp
  val fontSize5xl = 60.dp
  val textDisplay = "var(--cs-font-size-5xl)"
  val textH1 = "var(--cs-font-size-3xl)"
  val textH2 = "var(--cs-font-size-2xl)"
  val textH3 = "var(--cs-font-size-xl)"
  val textH4 = "var(--cs-font-size-lg)"
  val textBodyLg = "var(--cs-font-size-md)"
  val textBody = "var(--cs-font-size-base)"
  val textSecondary = "var(--cs-font-size-sm)"
  val textCaption = "var(--cs-font-size-xs)"
  val textEyebrow = "var(--cs-font-size-xs)"
  val letterSpacingTightEm = -0.01f
  val letterSpacingNormal = 0
  val letterSpacingCapsEm = 0.08f
  val iconSm = 16.dp
  val iconMd = 20.dp
  val iconLg = 24.dp

  // dark-theme color overrides
  val colorSurfacePageDark = Color(0xFF1A1108)
  val colorSurfacePanelDark = Color(0xFF221710)
  val colorSurfaceRaisedDark = Color(0xFF2B1E14)
  val colorTextPrimaryDark = Color(0xFFF5EAD9)
  val colorTextInverseDark = Color(0xFF1A1108)
  val colorTextAccentDark = Color(0xFFF4BA17)
  val colorTextMutedDark = Color(0xFFC9B7A3)
  val colorSemanticSuccessDark = Color(0xFF4ADE80)
  val colorSemanticDangerDark = Color(0xFFF87171)
  val colorSemanticWarningDark = Color(0xFFFBBF24)
  val colorSemanticInfoDark = Color(0xFF7CB2FB)
  val colorBorderDefaultDark = Color(0xFF4A3A2C)
  val colorLinkDark = Color(0xFFF4BA17)
  val colorLinkHoverDark = Color(0xFFF5EAD9)
  val componentButtonPrimaryBgDark = Color(0xFFF4BA17)
  val componentButtonPrimaryFgDark = Color(0xFF1A1108)
  val componentTextfieldBorderDefaultDark = Color(0xFF5A4636)

  // dark elemental accent packs (APCA-derived, v4.0.0)
  val accentBrightThoDark = Color(0xFFFEC42C)
  val accentStrongThoDark = Color(0xFF795507)
  val accentOnThoDark = Color(0xFFF5EAD9)
  val accentTintThoDark = Color(0xFF2F2203)
  val accentInkThoDark = Color(0xFFFEC849)
  val accentThoClayDark = Color(0xFFF3A372)
  val accentBrightThoClayDark = Color(0xFFF4C5A3)
  val accentStrongThoClayDark = Color(0xFF864927)
  val accentOnThoClayDark = Color(0xFFF5EAD9)
  val accentTintThoClayDark = Color(0xFF371C0B)
  val accentInkThoClayDark = Color(0xFFF7C8A6)
  val accentStrongThoSandDark = Color(0xFF725615)
  val accentOnThoSandDark = Color(0xFFF5EAD9)
  val accentTintThoSandDark = Color(0xFF2F2203)
  val accentInkThoSandDark = Color(0xFFEFDCB2)
  val accentHoaDark = Color(0xFFFB9E7A)
  val accentBrightHoaDark = Color(0xFFFEC099)
  val accentStrongHoaDark = Color(0xFF9F3405)
  val accentOnHoaDark = Color(0xFFF5EAD9)
  val accentTintHoaDark = Color(0xFF381B10)
  val accentInkHoaDark = Color(0xFFFEC5A1)
  val accentHoaLavaDark = Color(0xFFFE9982)
  val accentBrightHoaLavaDark = Color(0xFFFFBF9E)
  val accentOnHoaLavaDark = Color(0xFFF5EAD9)
  val accentTintHoaLavaDark = Color(0xFF391A13)
  val accentInkHoaLavaDark = Color(0xFFFFC4A5)
  val accentHoaPlasmaDark = Color(0xFFFD97A3)
  val accentBrightHoaPlasmaDark = Color(0xFFFDBECA)
  val accentStrongHoaPlasmaDark = Color(0xFFA91A43)
  val accentOnHoaPlasmaDark = Color(0xFFF5EAD9)
  val accentTintHoaPlasmaDark = Color(0xFF38191D)
  val accentInkHoaPlasmaDark = Color(0xFFFDC3CE)
  val accentThuyDark = Color(0xFF7FC0CE)
  val accentBrightThuyDark = Color(0xFFACD7E1)
  val accentOnThuyDark = Color(0xFFF5EAD9)
  val accentTintThuyDark = Color(0xFF042930)
  val accentInkThuyDark = Color(0xFFAFDAE4)
  val accentThuyOceanDark = Color(0xFF87B9DD)
  val accentBrightThuyOceanDark = Color(0xFFB2D6EA)
  val accentOnThuyOceanDark = Color(0xFFF5EAD9)
  val accentTintThuyOceanDark = Color(0xFF08273A)
  val accentInkThuyOceanDark = Color(0xFFB2D6EA)
  val accentStrongThuyMistDark = Color(0xFF3F5F65)
  val accentOnThuyMistDark = Color(0xFFF5EAD9)
  val accentTintThuyMistDark = Color(0xFF0F282C)
  val accentInkThuyMistDark = Color(0xFFC4DADD)
  val accentMocDark = Color(0xFF9BBE78)
  val accentBrightMocDark = Color(0xFFBFD88D)
  val accentStrongMocDark = Color(0xFF44622D)
  val accentOnMocDark = Color(0xFFF5EAD9)
  val accentTintMocDark = Color(0xFF1C290D)
  val accentInkMocDark = Color(0xFFC2DB90)
  val accentStrongMocBambooDark = Color(0xFF4C6421)
  val accentOnMocBambooDark = Color(0xFFF5EAD9)
  val accentTintMocBambooDark = Color(0xFF1F280A)
  val accentInkMocBambooDark = Color(0xFFC7D99E)
  val accentMocForestDark = Color(0xFF9EBE8D)
  val accentBrightMocForestDark = Color(0xFFBDD8A4)
  val accentOnMocForestDark = Color(0xFFF5EAD9)
  val accentTintMocForestDark = Color(0xFF19290F)
  val accentInkMocForestDark = Color(0xFFC0DBA7)
  val accentStrongKimDark = Color(0xFF675A4A)
  val accentOnKimDark = Color(0xFFF5EAD9)
  val accentTintKimDark = Color(0xFF2D220F)
  val accentInkKimDark = Color(0xFFDBCFB9)
  val accentKimSteelDark = Color(0xFFB2B6B6)
  val accentBrightKimSteelDark = Color(0xFFCCD0D0)
  val accentStrongKimSteelDark = Color(0xFF555B5D)
  val accentOnKimSteelDark = Color(0xFFF5EAD9)
  val accentTintKimSteelDark = Color(0xFF222525)
  val accentInkKimSteelDark = Color(0xFFCFD3D3)
  val accentKimTitaniumDark = Color(0xFFBFB3A5)
  val accentOnKimTitaniumDark = Color(0xFFF5EAD9)
  val accentTintKimTitaniumDark = Color(0xFF2B2217)
  val accentInkKimTitaniumDark = Color(0xFFD9CFC0)
}
