/**
 * Emit a DTCG-conformant theme overlay JSON.
 *
 * Output mirrors `tokens/colour.tokens.json` shape but contains ONLY the
 * tenant-specific overrides. The base values (Umber + Ochre anchor immutables,
 * semantic neutrals, etc.) come from `@cyberskill/tokens` and are never
 * overridden per RFC 2026-004 § Hard non-goals.
 */

export function emitThemeJson({ tenant, primary, accent, ramp }) {
  const tokens = {
    $schema: 'https://design-tokens.github.io/community-group/format-2025-10/schema.json',
    $description: `White-label theme overlay for tenant: ${tenant}. Generated by @cyberskill/theme-generator. Anchor immutables (Umber + Ochre) are NEVER overridden — see RFC 2026-004.`,
    color: {
      // Tenant accent slot — overrides color.accent.default per Part 13 §6.
      accent: {
        default: {
          $value: accent,
          $type: 'color',
          $extensions: {
            'com.cyberskill.role': 'tenant-accent',
            'com.cyberskill.generator': '@cyberskill/theme-generator@1.0.0',
            'com.cyberskill.tenant': tenant,
          },
        },
      },
      // Tenant primary slot — overrides color.brand.primary per Part 13 §6.
      brand: {
        primary: {
          $value: primary,
          $type: 'color',
          $extensions: {
            'com.cyberskill.role': 'tenant-primary',
            'com.cyberskill.generator': '@cyberskill/theme-generator@1.0.0',
            'com.cyberskill.tenant': tenant,
          },
        },
        ramp: ramp.reduce((acc, v, i) => {
          acc[`${(i * 100).toString()}`] = {
            $value: v,
            $type: 'color',
            $description: `12-step ramp generated from primary at perceptual lightness ${(0.05 + (0.92 * i) / 11).toFixed(3)}.`,
          };
          return acc;
        }, {}),
      },
    },
  };
  return tokens;
}
