// cyberskill.world — real bilingual copy (EN + VN) lifted from the product
// i18n dictionaries + content. window.SITE_COPY[locale]. Vietnamese-first.
window.SITE_COPY = {
  en: {
    nav: ["Services", "Work", "Process", "Careers", "Contact"],
    langLabel: "Tiếng Việt",
    eyebrow: "A Saigon studio that turns will into working software. Since 2020.",
    slogan: "Turn Your Will Into Real",
    sub: "Hiện Thực Hoá Ý Chí",
    lead: "Lumi, our golden genie, takes a clear wish and helps the human team turn it into software your people actually run — built to ship, and built to last.",
    wishPlaceholder: "Make a wish… a faster checkout, an app, a tool",
    wishCta: "Make a wish",
    talk: "Talk to Lumi",
    marquee: ["Web apps", "Mobile apps", "Internal systems", "Automation", "Design systems", "Built to last"],
    servicesTitle: "What we build",
    servicesLead: "Three focused practices. One team that answers for the result.",
    services: [
      { icon: "sparkle", t: "Web & mobile apps", s: "Product apps your customers reach for — fast, accessible, bilingual by default.", o: ["Web apps", "Mobile apps", "Design systems"] },
      { icon: "chat", t: "Internal systems & automation", s: "The tools your team runs on: dashboards, workflows, and the automation behind them.", o: ["Internal systems", "Automation"] },
      { icon: "check", t: "Built to last", s: "Shipped software that keeps running — tested, documented, handed over cleanly.", o: ["Testing", "Docs", "Handover"] },
    ],
    processTitle: "The arc of a wish",
    processLead: "Every project follows one arc: from a clear wish to software running in the real world.",
    steps: [
      { n: "01", t: "Make a wish", s: "Tell us the outcome in a sentence or two. We reply within one business day." },
      { n: "02", t: "Shape it", s: "A small senior team scopes the work and is honest about trade-offs." },
      { n: "03", t: "Build to ship", s: "Short cycles, real software you can run — not slideware." },
      { n: "04", t: "Built to last", s: "Tested, documented, handed over. It keeps running after we leave." },
    ],
    careersTitle: "Build with us",
    careersLead: "We hire for craft and care — senior, small, and honest about trade-offs.",
    careersCta: "See open roles",
    contactTitle: "Tell us your wish",
    contactLead: "Send a short note. We reply within one business day.",
    form: { name: "Your name", email: "Work email", company: "Company", message: "Anything we should know?", submit: "Send", optional: "optional", trust: "Your details go straight to the team. We never share them." },
    genie: { title: "Lumi · CyberSkill’s golden genie", greeting: "Hello, I’m Lumi. Think of me as a friendly guide: tell me a wish, and I’ll share plain advice before asking for anything. When a wish is clear, it goes to a real person on the team.", placeholder: "Type your wish…", send: "Send", chips: ["A web app", "An internal tool", "A design system"] },
    footerRights: "All rights reserved.",
    footerLinks: ["Privacy", "Accessibility", "Terms"],
  },
  vi: {
    nav: ["Dịch vụ", "Dự án", "Quy trình", "Tuyển dụng", "Liên hệ"],
    langLabel: "English",
    eyebrow: "Studio Sài Gòn. Biến ý chí thành phần mềm chạy thật. Từ năm 2020.",
    slogan: "Hiện Thực Hoá Ý Chí",
    sub: "Turn Your Will Into Real",
    lead: "Lumi, thần đèn vàng của CyberSkill, cùng đội ngũ biến điều ước rõ thành phần mềm đội bạn dùng mỗi ngày: bàn giao được, dùng lâu được.",
    wishPlaceholder: "Ước một điều… thanh toán nhanh hơn, một ứng dụng, một công cụ",
    wishCta: "Ước điều này",
    talk: "Trò chuyện với Lumi",
    marquee: ["Ứng dụng web", "Ứng dụng di động", "Hệ thống nội bộ", "Tự động hóa", "Hệ thống thiết kế", "Bền bỉ lâu dài"],
    servicesTitle: "Chúng tôi xây dựng những gì",
    servicesLead: "Ba mảng chuyên sâu. Một đội chịu trách nhiệm đến kết quả cuối cùng.",
    services: [
      { icon: "sparkle", t: "Ứng dụng web & di động", s: "Sản phẩm khách hàng dùng mỗi ngày — nhanh, dễ tiếp cận, song ngữ mặc định.", o: ["Ứng dụng web", "Di động", "Hệ thống thiết kế"] },
      { icon: "chat", t: "Hệ thống nội bộ & tự động hóa", s: "Công cụ đội bạn vận hành: bảng điều khiển, quy trình và tự động hóa phía sau.", o: ["Hệ thống nội bộ", "Tự động hóa"] },
      { icon: "check", t: "Bền bỉ lâu dài", s: "Phần mềm bàn giao vẫn chạy tốt — được kiểm thử, tài liệu đầy đủ, bàn giao gọn.", o: ["Kiểm thử", "Tài liệu", "Bàn giao"] },
    ],
    processTitle: "Hành trình của một điều ước",
    processLead: "Mỗi dự án một hành trình: từ điều ước rõ đến phần mềm chạy giữa đời thật.",
    steps: [
      { n: "01", t: "Ước một điều", s: "Kể kết quả bạn muốn trong một hai câu. Chúng tôi phản hồi trong một ngày làm việc." },
      { n: "02", t: "Định hình", s: "Đội nhỏ, kinh nghiệm bóc tách công việc và nói thẳng về đánh đổi." },
      { n: "03", t: "Xây để bàn giao", s: "Chu kỳ ngắn, phần mềm chạy thật — không phải slide." },
      { n: "04", t: "Dùng lâu được", s: "Kiểm thử, tài liệu, bàn giao. Vẫn chạy tốt sau khi chúng tôi rời đi." },
    ],
    careersTitle: "Cùng chúng tôi kiến tạo",
    careersLead: "Tuyển người có tay nghề và chỉn chu — đội gọn, kinh nghiệm, nói thẳng đánh đổi.",
    careersCta: "Xem vị trí đang mở",
    contactTitle: "Kể chúng tôi nghe điều bạn ước",
    contactLead: "Một lời nhắn ngắn là đủ. Chúng tôi phản hồi trong một ngày làm việc.",
    form: { name: "Tên của bạn", email: "Email công việc", company: "Công ty", message: "Bạn muốn chia sẻ thêm điều gì?", submit: "Gửi", optional: "không bắt buộc", trust: "Thông tin của bạn được gửi thẳng đến đội ngũ. Chúng tôi không chia sẻ cho bên thứ ba." },
    genie: { title: "Lumi · thần đèn vàng CyberSkill", greeting: "Chào bạn, mình là Lumi. Cứ kể mình một điều ước; mình tư vấn trước, chỉ xin thông tin khi bạn muốn gửi. Điều ước rõ sẽ được chuyển cho người thật trong đội.", placeholder: "Viết điều ước của bạn…", send: "Gửi", chips: ["Một ứng dụng web", "Công cụ nội bộ", "Hệ thống thiết kế"] },
    footerRights: "Bảo lưu mọi quyền.",
    footerLinks: ["Quyền riêng tư", "Khả năng tiếp cận", "Điều khoản"],
  },
};
