#!/usr/bin/env node
/*
 * @cyberskill/style-packs build.
 * A style pack layers RENDER-SURFACE decisions (fills, blur, borders, shadows,
 * radii, type/motion treatment) over the immutable Umber + Ochre anchors.
 *
 * Hard rules enforced here (build fails if violated):
 *   1. No pack CSS may redefine the brand anchor tokens
 *      (--cs-color-brand-umber / --cs-color-brand-ochre).
 *   2. Every pack CSS rule must be scoped under [data-cs-style="<id>"] so a pack
 *      only applies when explicitly selected, and never leaks into the core.
 *   3. status is derived, not declared: "shipped" iff a src/css/<id>.css exists,
 *      else "implementable" (UI-viable, CSS pending) or "vocabulary".
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { createHash } from "node:crypto";

const ROOT = resolve(import.meta.dirname, "..");
const SRC = resolve(ROOT, "src/styles.catalog.json");
const CSS_DIR = resolve(ROOT, "src/css");
const DIST = resolve(ROOT, "dist");

const catalog = JSON.parse(readFileSync(SRC, "utf8"));
const ANCHORS = catalog.anchorsImmutable;
const errors = [];

function ensure(p) { mkdirSync(p, { recursive: true }); }
function write(p, body) { ensure(dirname(p)); writeFileSync(p, body); }

const REQUIRED = ["id", "name", "category", "mood", "bestFor", "coreElements",
  "anchorMapping", "surfaceTreatment", "uiImplementable", "accessibilityNote"];

const seen = new Set();
const records = [];

for (const pack of catalog.packs) {
  for (const f of REQUIRED) {
    if (pack[f] === undefined || pack[f] === null || pack[f] === "") {
      errors.push(`${pack.id ?? "?"}: missing field "${f}"`);
    }
  }
  if (seen.has(pack.id)) errors.push(`duplicate pack id: ${pack.id}`);
  seen.add(pack.id);

  const cssFile = resolve(CSS_DIR, `${pack.id}.css`);
  const hasCss = existsSync(cssFile);
  let css = "";
  if (hasCss) {
    css = readFileSync(cssFile, "utf8");
    // Rule 1: immutability guard.
    if (/--cs-color-brand-(umber|ochre)\s*:/.test(css)) {
      errors.push(`${pack.id}: CSS redefines an immutable brand anchor token (forbidden)`);
    }
    // Rule 2: scoping guard — every top-level selector must include the pack scope.
    const scope = `[data-cs-style="${pack.id}"]`;
    const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "");
    const selectors = withoutComments
      .split("}")
      .map((block) => block.split("{")[0].trim())
      .filter(Boolean)
      .filter((sel) => !sel.startsWith("@"));
    for (const sel of selectors) {
      // allow @media/@supports inner selectors only if they carry the scope
      if (!sel.includes(scope)) {
        errors.push(`${pack.id}: selector not scoped to ${scope} -> "${sel.slice(0, 80)}"`);
        break;
      }
    }
  }

  const status = hasCss ? "shipped" : (pack.uiImplementable ? "implementable" : "vocabulary");
  records.push({ ...pack, status, css: hasCss ? `dist/css/${pack.id}.css` : null });
}

// Catch orphan CSS files with no manifest.
if (existsSync(CSS_DIR)) {
  for (const f of readdirSync(CSS_DIR)) {
    if (!f.endsWith(".css")) continue;
    const id = f.replace(/\.css$/, "");
    if (!seen.has(id)) errors.push(`orphan CSS with no manifest entry: src/css/${f}`);
  }
}

if (errors.length) {
  console.error("[style-packs] build failed:");
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

const shipped = records.filter((r) => r.status === "shipped");

// 1. Per-pack CSS copied into dist + a single combined stylesheet.
const combined = ["/* Generated by @cyberskill/style-packs. Do not edit directly. */",
  "/* Each block applies only under its [data-cs-style] scope. Brand anchors are never overridden. */", ""];
for (const r of shipped) {
  const css = readFileSync(resolve(CSS_DIR, `${r.id}.css`), "utf8");
  write(resolve(DIST, "css", `${r.id}.css`), css);
  combined.push(`/* ===== ${r.name} (${r.id}) ===== */`, css.trim(), "");
}
write(resolve(DIST, "style-packs.css"), combined.join("\n") + "\n");

// 2. Registry index.
const registry = {
  package: "@cyberskill/style-packs",
  version: catalog.version,
  generatedAt: new Date().toISOString(),
  sourceHash: createHash("sha256").update(readFileSync(SRC)).digest("hex"),
  anchorsImmutable: ANCHORS,
  selector: 'data-cs-style="<id>"',
  counts: {
    total: records.length,
    shipped: records.filter((r) => r.status === "shipped").length,
    implementable: records.filter((r) => r.status === "implementable").length,
    vocabulary: records.filter((r) => r.status === "vocabulary").length
  },
  packs: records.map(({ css, ...rest }) => ({ ...rest, css }))
};
write(resolve(DIST, "registry.json"), JSON.stringify(registry, null, 2) + "\n");

// 3. Human-readable catalog.
const md = [
  "# CyberSkill Style Packs — Catalog",
  "",
  `Generated from \`src/styles.catalog.json\`. ${records.length} styles · ${registry.counts.shipped} shipped (CSS render layer) · ${registry.counts.implementable} UI-implementable · ${registry.counts.vocabulary} vocabulary.`,
  "",
  "Every pack layers render-surface decisions over the **immutable** Umber `#45210E` + Ochre `#F4BA17` anchors. Select with `data-cs-style=\"<id>\"`; compose with `data-theme` for light/dark.",
  "",
  "| Status | id | Name | Category | Mood | Best for |",
  "|---|---|---|---|---|---|",
  ...records.map((r) => `| ${r.status === "shipped" ? "✅ shipped" : r.status === "implementable" ? "🟡 impl." : "📓 vocab"} | \`${r.id}\` | ${r.name} | ${r.category} | ${r.mood} | ${r.bestFor.join("; ")} |`),
  ""
].join("\n");
write(resolve(DIST, "catalog.md"), md);

console.log(`[style-packs] ${records.length} packs (${registry.counts.shipped} shipped, ${registry.counts.implementable} implementable, ${registry.counts.vocabulary} vocabulary)`);
